# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }
gem "jekyll"
gem 'jekyll-feed'
gem 'jekyll-readme-index'
gem 'jemoji'
gem 'webrick'
gem 'google-protobuf', force_ruby_platform: true if RUBY_PLATFORM.include?('linux-musl')

# gem "rails"
